spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/corevia
    username: corevia
    password: corevia
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
