spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/corevia
    username: corevia
    password: corevia
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  h2:
    console:
      enabled: false
